version: '3.8'

services:
  web-sdk-tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44780:80"
      - "48417:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service for local development
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "44780:3000"
      - "48417:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    profiles:
      - dev